### ISSUE TITLE
OTP UI Process

### ISSUE THREAD

**Issue by Sakshamag21** [Billing-360/Billing-360-Dev#1]
When you go for sending an OTP by clicking the button, user was not able to know that top is either sended or not as there are no hovering or clicking effect on button and not any loading symbol appears which causes a confusion that either the OTP is ended or not and user clicks multiple times to ensure that it is ended which results in many OTP getting ended to the mail and user was not able to recognize which one is to enter or not.

This is a UI problem and can be solved by changing few things

**Comment by nipunnohria** [comment]
This has been resolved, a loading cursor has been added.  
As for confusion in OTPs, the latest sent OTP on the mail is the one to be entered.
