### ISSUE TITLE
OTP verification is failing

### ISSUE THREAD

**Issue by Sakshamag21** [Billing-360/Billing-360-Dev#2]
![Screenshot (1321)](https://github.com/Billing-360/Billing-360-Dev/assets/107304333/a841c9fb-74ab-4399-9978-17229e817bc6)
![Screenshot (1322)](https://github.com/Billing-360/Billing-360-Dev/assets/107304333/a01a5b21-c6c6-4499-bc9f-dea5b72272a3)

**Comment by pallavgoyal136** [comment]
It seems that you have entered an older OTP, please try entering the latest OTP received
