### ISSUE TITLE
Batch expiry date and stock quantity

### ISSUE THREAD

**Issue by Sakshamag21** [Billing-360/Billing-360-Dev#3]
If batch is expired means that product is not good not soldable  as per current date then stock should be removed ideally but it is not
![Screenshot (1324)](https://github.com/Billing-360/Billing-360-Dev/assets/107304333/025a9246-bb77-4b43-b78d-0fa0746d105b)

**Comment by pallavgoyal136** [comment]
It's a decision we took because whether to sell an expired item or not is the shopkeeper's moral decision, as a software it's responsibility is to alert the user which it is already doing by marking it with red color
