### ISSUE TITLE
Email verification process not exsist

### ISSUE THREAD

**Issue by Sakshamag21** [Billing-360/Billing-360-Dev#4]
There is no provision for checking the email of the buyer of a stock which happens  during the billing process.
![WhatsApp Image 2024-04-07 at 21 00 45_f3156a94](https://github.com/Billing-360/Billing-360-Dev/assets/107304333/3201125c-352c-4c86-a220-fc6dd884c81a)

**Comment by pallavgoyal136** [comment]
As far as this issue is concerned as far the use case of our software is concerned it is the responsibility of the customer to correctly tell the mail to shopkeeper failing to do that will lead him to not receiving notification regarding the invoice
Kindly let us know if there is still a problem
