### ISSUE TITLE
Database updation issues

### ISSUE THREAD

**Issue by Sakshamag21** [Billing-360/Billing-360-Dev#5]
The database is not reflecting the database chances in the website during the following:-
After we clear the dues of a person if we want to create another profile of a different person with the same email ID, we can't do it because of the restriction of singular email ID, and hence the dues will be added to the name of the original person with that email ID.
Ideally, after a person clears his/her dues, the database should delete his details.

**Comment by pallavgoyal136** [comment]
As far as 'different person with same email id' is concerned, this a very simple assumption which is made everywhere that an email id is allocated to a single person and it is practically not possible that two people together combined make one email, if suppose by chance such people arrive then the assumption of is that the invoice or credit is being issued against the mail id even if it is shared by two people.
Kindly let us know if you still think that it is a problem
